minecraft:fire_protection: 4
minecraft:sharpness: 5
minecraft:flame: 1
minecraft:aqua_affinity: 1
minecraft:punch: 2
minecraft:loyalty: 3
minecraft:depth_strider: 3
minecraft:vanishing_curse: 1
minecraft:unbreaking: 3
minecraft:knockback: 2
minecraft:luck_of_the_sea: 3
minecraft:binding_curse: 1
minecraft:fortune: 3
minecraft:protection: 4
minecraft:efficiency: 5
minecraft:mending: 1
minecraft:frost_walker: 2
minecraft:lure: 3
minecraft:looting: 3
minecraft:blast_protection: 4
minecraft:smite: 5
minecraft:fire_aspect: 2
minecraft:channeling: 1
minecraft:sweeping: 3
minecraft:thorns: 3
minecraft:bane_of_arthropods: 5
minecraft:respiration: 3
minecraft:riptide: 3
minecraft:silk_touch: 1
minecraft:projectile_protection: 4
minecraft:impaling: 5
minecraft:feather_falling: 4
minecraft:power: 5
minecraft:infinity: 1